Refatoração
Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao pull request #23
Opened 2022-07-26 01:52 UTC by fellipe-araujo

2022-07-26 21:54 UTC, ErickGiffoni reviewed
Outros pontos:
- O \__pycache__ apesar de estar no gitignore subiu junto no push (não fazer git add . )
- o arquivo db.sqlite3 também acabou subindo, mas acho q não precisa
- Ainda tem muitas ocorrências da palavra "sessão", apesar de não ter mais uma sessão. O sistema tem produção e lotes né ? To com medo de dar confusão
- A pasta das migrations tbm subiu 🤣

2022-07-26 21:54 UTC, ErickGiffoni commented on backend/carrossel/urls.py
> +route.register(r'base',SessaoViewSets.baseViewSets, basename='base')
Qual a diferença dessa basename=base e da que está ali em baixo,
basename=baseProdução ?
Teria algum nome pra não confundir ?

2022-07-26 21:54 UTC, ErickGiffoni commented on frontend/src/components/SideBar.tsx
> +  const [sessionActive, setSessionActive] = useState('production-session');
production-session poderia ser só production ?

2022-07-26 21:54 UTC, ErickGiffoni commented on frontend/src/services/productionService.ts
> +  // }
Não tem problema o código comentado... mas se der pode apagar =)

2022-07-26 22:18 UTC, mateusbrandaot commented on backend/carrossel/urls.py
> +route.register(r'base',SessaoViewSets.baseViewSets, basename='base')
baseProducao é a entidade gerada a partir do relacionamento da producao com o tipo da base.

2022-07-27 02:02 UTC, SamButers reviewed
Aparentemente os lotes não estão sendo criados automaticamente quando uma produção é criada.

2022-07-27 18:09 UTC, fellipe-araujo commented on frontend/src/components/SideBar.tsx
> +  const [sessionActive, setSessionActive] = useState('production-session');
Esse "session" seria a sessão que está ativa, ou melhor, a página que está ativa como, por exemplo, página de produção, página de dashboard, página de tintas, etc. Porém, fiz as alterações para remover o "session" das páginas.

2022-07-27 18:10 UTC, fellipe-araujo commented on frontend/src/services/productionService.ts
> +  // }
Antes de abrir o PR, removi muitos comentários que tinha no código e acabei esquecendo desse e de outros. Obrigado pelo retorno, já removi todos!

2022-07-27 18:12 UTC, fellipe-araujo commented on backend/carrossel/urls.py
> +route.register(r'base',SessaoViewSets.baseViewSets, basename='base')
Não sei o que houve para as pastas __pycache__, migrations e o arquivo db.sqlite3 subirem mesmo estes estando no arquivo .gitignore. Porém, já removi todos e acredito que agora eles não vão mais subir.

2022-07-27 20:51 UTC, Projeto-Carrossel-Serigrafia-PI2 commented on backend/carrossel/urls.py
> +route.register(r'base',SessaoViewSets.baseViewSets, basename='base')
Show

2022-07-27 21:20 UTC, SamButers approved these changes

2022-07-27 21:38 UTC, Projeto-Carrossel-Serigrafia-PI2 requested changes
### Melhorias antes do merge
 
- Não informei a base da tinta mas a produção foi criada
- criei uma tinta (trocar esse nome para base da tinta) com temperatura de secagem 1000C e tempo de secagem 1000000000 segundos -> tinha q dar erro tbm
- cliquei pra deletar a tinta e não foi apresentado um "tem certeza?" - ai acusou q deletou mas não atualizou a tela, a tinta continuou lá até dar o refresh
- quando não houver tinta, colocar na tela uma mensagem q não tem tinta, pro usuário saber q tem q cadastrar
- produção iniciada mesmo com qtd de camisas igual a 0 e velocidade 0 tbm -> tinha q dar erro pra qualquer caso desse
- quando a produção começa, não acontece nada -> acho que deveria redirecionar o usuário para o dashboard né ?

2022-07-28 20:54 UTC, fellipe-araujo commented
A respeito de criar uma base de tinta com altos valores de temperatura de secagem e tempo de secagem não foi feito, pois essa funcionalidade ainda não está implementada (definição de limites). Acredito que na própria issue de fazer essa definição, pode-se configurar isso no front-end também. @ErickGiffoni

2022-07-29 13:38 UTC, ErickGiffoni commented
> A respeito de criar uma base de tinta com altos valores de temperatura de secagem e tempo de secagem não foi feito, pois essa funcionalidade ainda não está implementada (definição de limites). Acredito que na própria issue de fazer essa definição, pode-se configurar isso no front-end também. @ErickGiffoni

Perfeito, estamos dependendo do @thallysbraz finalizar as issues desses limites.

2022-07-29 14:01 UTC, ErickGiffoni commented
Ok, acabei de testar, tudo certo (fora a questão dos limites de temp e de tempo)
Aprovando

2022-07-29 14:02 UTC, ErickGiffoni approved these changes

2022-07-29 14:03 UTC, merged