Dashboard - Gráfico da análise da qualidade dinâmico
Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao pull request #36
Opened 2022-08-31 16:59 UTC by fellipe-araujo

## Issue relacionada

* #34

2022-08-31 19:21 UTC, mateusbrandaot approved these changes

2022-09-06 18:58 UTC, ErickGiffoni requested changes
Add no requirements do back:
numpy==1.23.0

2022-09-07 18:25 UTC, ErickGiffoni commented
@fellipe-araujo faz a adição ai assim que der

2022-09-07 19:19 UTC, ErickGiffoni requested changes
Permitir a navegação para a página do Relatório de Qualidade quando uma produção estiver pausada.

2022-09-09 14:00 UTC, ErickGiffoni approved these changes

2022-09-09 14:00 UTC, merged